version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  reviewers:
  - trezy
  ignore:
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.12.16
    - 7.12.17
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: "@babel/cli"
    versions:
    - 7.12.10
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.14
  - dependency-name: faker
    versions:
    - 5.4.0
    - 5.5.1
    - 5.5.2
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
    - 7.12.16
    - 7.12.17
    - 7.13.10
    - 7.13.12
    - 7.13.8
    - 7.13.9
  - dependency-name: "@babel/node"
    versions:
    - 7.12.10
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.10
  - dependency-name: chai
    versions:
    - 4.3.0
    - 4.3.3
  - dependency-name: mocha
    versions:
    - 8.2.1
    - 8.3.0
    - 8.3.1
  - dependency-name: jsdoc-to-markdown
    versions:
    - 7.0.0
  - dependency-name: firebase-admin
    versions:
    - 9.4.2
    - 9.5.0
  - dependency-name: systeminformation
    versions:
    - 4.34.5
    - 4.34.9
  - dependency-name: nodemon
    versions:
    - 2.0.7
  - dependency-name: date-and-time
    versions:
    - 0.14.2
  - dependency-name: "@babel/register"
    versions:
    - 7.12.10
  - dependency-name: ini
    versions:
    - 1.3.7
  - dependency-name: "@babel/plugin-proposal-private-methods"
    versions:
    - 7.12.1
  - dependency-name: "@babel/plugin-proposal-class-properties"
    versions:
    - 7.12.1
