import 'routes/fdgt/v1/commands'
import 'routes/fdgt/v1/commands/[command]'
import 'routes/fdgt/v1/commands/[command]/docs'
import 'routes/fdgt/v1/commands/[command]/params'
import 'routes/fdgt/v1/contributors'
import 'routes/fdgt/v1/sponsors'
